package UI;

import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Kirby
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        //panelVenta.setVisible(false);
        panel_menu.setVisible(false);
        panel_Admin.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVenta = new javax.swing.JPanel();
        panelLista = new javax.swing.JPanel();
        listaVacia = new javax.swing.JLabel();
        panelSumaCostos = new javax.swing.JPanel();
        lab_SubTotal = new javax.swing.JLabel();
        lab_Impuestos = new javax.swing.JLabel();
        labTotal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        subTotal = new javax.swing.JLabel();
        impuestos = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        panelEditCompra = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        bt_CancelarCompra = new javax.swing.JPanel();
        icon_CancelarCompra = new javax.swing.JLabel();
        panelEditArticulos = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        bt_EliminarProducto = new javax.swing.JPanel();
        icon_EliminarProducto = new javax.swing.JLabel();
        PanelVistaProductos = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tf_BuscarProducto = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        panelProductos = new javax.swing.JPanel();
        bt_RetornoVategoria = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PanelCategoria = new javax.swing.JPanel();
        Producto = new javax.swing.JPanel();
        bt_Menu = new javax.swing.JPanel();
        icon_menu = new javax.swing.JLabel();
        bt_BuscarProducto = new javax.swing.JPanel();
        icon_BuscarProducto = new javax.swing.JLabel();
        Lab_BuscarProducto = new javax.swing.JLabel();
        panel_menu = new javax.swing.JPanel();
        bt_cerrarMenu = new javax.swing.JPanel();
        icon_cerrarMenu = new javax.swing.JLabel();
        bt_PanelAdmin = new javax.swing.JPanel();
        icon_PanelAdmin = new javax.swing.JLabel();
        panel_Admin = new javax.swing.JPanel();
        panel_menuOpciones = new javax.swing.JPanel();
        bt_Productos = new javax.swing.JPanel();
        icon_Productos = new javax.swing.JLabel();
        panel_Activida = new javax.swing.JPanel();
        panel_AdminProductos = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bt_VolverPanelVenta = new javax.swing.JPanel();
        icon_VolverPanelVenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(822, 419));

        panelVenta.setBackground(new java.awt.Color(51, 51, 51));
        panelVenta.setMinimumSize(new java.awt.Dimension(822, 419));

        panelLista.setBackground(new java.awt.Color(51, 51, 51));
        panelLista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        listaVacia.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        listaVacia.setForeground(new java.awt.Color(204, 204, 204));
        listaVacia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listaVacia.setText("No hay artículos");
        listaVacia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        panelSumaCostos.setBackground(new java.awt.Color(51, 51, 51));

        lab_SubTotal.setForeground(new java.awt.Color(255, 255, 255));
        lab_SubTotal.setText("Subtotal");

        lab_Impuestos.setForeground(new java.awt.Color(255, 255, 255));
        lab_Impuestos.setText("Impuestos");

        labTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labTotal.setForeground(new java.awt.Color(255, 255, 255));
        labTotal.setText("TOTAL");

        subTotal.setForeground(new java.awt.Color(255, 255, 255));
        subTotal.setText("0.00");

        impuestos.setForeground(new java.awt.Color(255, 255, 255));
        impuestos.setText("0.00");

        total.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setText("0.00");

        javax.swing.GroupLayout panelSumaCostosLayout = new javax.swing.GroupLayout(panelSumaCostos);
        panelSumaCostos.setLayout(panelSumaCostosLayout);
        panelSumaCostosLayout.setHorizontalGroup(
            panelSumaCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelSumaCostosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSumaCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(panelSumaCostosLayout.createSequentialGroup()
                        .addComponent(lab_SubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subTotal))
                    .addGroup(panelSumaCostosLayout.createSequentialGroup()
                        .addComponent(lab_Impuestos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(impuestos))
                    .addGroup(panelSumaCostosLayout.createSequentialGroup()
                        .addComponent(labTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(total)))
                .addContainerGap())
            .addComponent(jSeparator3)
        );
        panelSumaCostosLayout.setVerticalGroup(
            panelSumaCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSumaCostosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSumaCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_SubTotal)
                    .addComponent(subTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSumaCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_Impuestos)
                    .addComponent(impuestos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(panelSumaCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTotal)
                    .addComponent(total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelEditCompra.setBackground(new java.awt.Color(51, 51, 51));

        bt_CancelarCompra.setBackground(java.awt.Color.darkGray);
        bt_CancelarCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        bt_CancelarCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_CancelarCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_CancelarCompraMouseExited(evt);
            }
        });

        icon_CancelarCompra.setBackground(java.awt.Color.darkGray);
        icon_CancelarCompra.setForeground(new java.awt.Color(255, 255, 255));
        icon_CancelarCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_CancelarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/basura.png"))); // NOI18N
        icon_CancelarCompra.setText("Cancelar");

        javax.swing.GroupLayout bt_CancelarCompraLayout = new javax.swing.GroupLayout(bt_CancelarCompra);
        bt_CancelarCompra.setLayout(bt_CancelarCompraLayout);
        bt_CancelarCompraLayout.setHorizontalGroup(
            bt_CancelarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_CancelarCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_CancelarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bt_CancelarCompraLayout.setVerticalGroup(
            bt_CancelarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_CancelarCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_CancelarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelEditCompraLayout = new javax.swing.GroupLayout(panelEditCompra);
        panelEditCompra.setLayout(panelEditCompraLayout);
        panelEditCompraLayout.setHorizontalGroup(
            panelEditCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5)
            .addGroup(panelEditCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_CancelarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEditCompraLayout.setVerticalGroup(
            panelEditCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditCompraLayout.createSequentialGroup()
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_CancelarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelEditArticulos.setBackground(new java.awt.Color(51, 51, 51));

        jSeparator2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        bt_EliminarProducto.setBackground(java.awt.Color.darkGray);
        bt_EliminarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_EliminarProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_EliminarProductoMouseExited(evt);
            }
        });

        icon_EliminarProducto.setForeground(new java.awt.Color(255, 255, 255));
        icon_EliminarProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_EliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerca.png"))); // NOI18N
        icon_EliminarProducto.setText("Eliminar");

        javax.swing.GroupLayout bt_EliminarProductoLayout = new javax.swing.GroupLayout(bt_EliminarProducto);
        bt_EliminarProducto.setLayout(bt_EliminarProductoLayout);
        bt_EliminarProductoLayout.setHorizontalGroup(
            bt_EliminarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_EliminarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_EliminarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        bt_EliminarProductoLayout.setVerticalGroup(
            bt_EliminarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_EliminarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_EliminarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelEditArticulosLayout = new javax.swing.GroupLayout(panelEditArticulos);
        panelEditArticulos.setLayout(panelEditArticulosLayout);
        panelEditArticulosLayout.setHorizontalGroup(
            panelEditArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelEditArticulosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_EliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEditArticulosLayout.setVerticalGroup(
            panelEditArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditArticulosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_EliminarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelListaLayout = new javax.swing.GroupLayout(panelLista);
        panelLista.setLayout(panelListaLayout);
        panelListaLayout.setHorizontalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEditArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelEditCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelListaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSumaCostos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelListaLayout.createSequentialGroup()
                        .addComponent(listaVacia, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelListaLayout.setVerticalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaLayout.createSequentialGroup()
                .addComponent(panelEditArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
<<<<<<< HEAD
                .addGap(44, 44, 44)
=======
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
>>>>>>> d7b9ada027d9aa99766604c514e643cb154cb6cd
                .addComponent(listaVacia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(panelSumaCostos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(panelEditCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelVistaProductos.setBackground(new java.awt.Color(51, 51, 51));
        PanelVistaProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        tf_BuscarProducto.setBackground(new java.awt.Color(51, 51, 51));
        tf_BuscarProducto.setForeground(new java.awt.Color(255, 255, 255));
        tf_BuscarProducto.setToolTipText("");
        tf_BuscarProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        tf_BuscarProducto.setFocusable(false);
        tf_BuscarProducto.setName("a"); // NOI18N
        tf_BuscarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_BuscarProductoMouseClicked(evt);
            }
        });
        tf_BuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_BuscarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tf_BuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(tf_BuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 4, Short.MAX_VALUE))
        );

        panelProductos.setBackground(new java.awt.Color(51, 51, 51));
        panelProductos.setAutoscrolls(true);

        bt_RetornoVategoria.setBackground(java.awt.Color.darkGray);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/girar-a-la-izquierda.png"))); // NOI18N

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Volver");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout bt_RetornoVategoriaLayout = new javax.swing.GroupLayout(bt_RetornoVategoria);
        bt_RetornoVategoria.setLayout(bt_RetornoVategoriaLayout);
        bt_RetornoVategoriaLayout.setHorizontalGroup(
            bt_RetornoVategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_RetornoVategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bt_RetornoVategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        bt_RetornoVategoriaLayout.setVerticalGroup(
            bt_RetornoVategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_RetornoVategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelCategoriaLayout = new javax.swing.GroupLayout(PanelCategoria);
        PanelCategoria.setLayout(PanelCategoriaLayout);
        PanelCategoriaLayout.setHorizontalGroup(
            PanelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        PanelCategoriaLayout.setVerticalGroup(
            PanelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ProductoLayout = new javax.swing.GroupLayout(Producto);
        Producto.setLayout(ProductoLayout);
        ProductoLayout.setHorizontalGroup(
            ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        ProductoLayout.setVerticalGroup(
            ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_RetornoVategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_RetornoVategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelVistaProductosLayout = new javax.swing.GroupLayout(PanelVistaProductos);
        PanelVistaProductos.setLayout(PanelVistaProductosLayout);
        PanelVistaProductosLayout.setHorizontalGroup(
            PanelVistaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVistaProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelVistaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelVistaProductosLayout.setVerticalGroup(
            PanelVistaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVistaProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bt_Menu.setBackground(java.awt.Color.darkGray);
        bt_Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_MenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_MenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_MenuMouseExited(evt);
            }
        });

        icon_menu.setBackground(new java.awt.Color(51, 51, 51));
        icon_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.png"))); // NOI18N

        javax.swing.GroupLayout bt_MenuLayout = new javax.swing.GroupLayout(bt_Menu);
        bt_Menu.setLayout(bt_MenuLayout);
        bt_MenuLayout.setHorizontalGroup(
            bt_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icon_menu)
                .addContainerGap())
        );
        bt_MenuLayout.setVerticalGroup(
            bt_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_menu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bt_BuscarProducto.setBackground(java.awt.Color.darkGray);
        bt_BuscarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_BuscarProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_BuscarProductoMouseExited(evt);
            }
        });

        icon_BuscarProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_BuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N

        Lab_BuscarProducto.setForeground(new java.awt.Color(255, 255, 255));
        Lab_BuscarProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lab_BuscarProducto.setText("Buscar");

        javax.swing.GroupLayout bt_BuscarProductoLayout = new javax.swing.GroupLayout(bt_BuscarProducto);
        bt_BuscarProducto.setLayout(bt_BuscarProductoLayout);
        bt_BuscarProductoLayout.setHorizontalGroup(
            bt_BuscarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_BuscarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bt_BuscarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lab_BuscarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(icon_BuscarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        bt_BuscarProductoLayout.setVerticalGroup(
            bt_BuscarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_BuscarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_BuscarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lab_BuscarProducto)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelVentaLayout = new javax.swing.GroupLayout(panelVenta);
        panelVenta.setLayout(panelVentaLayout);
        panelVentaLayout.setHorizontalGroup(
            panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVentaLayout.createSequentialGroup()
                        .addComponent(panelLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelVistaProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelVentaLayout.createSequentialGroup()
                        .addComponent(bt_BuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelVentaLayout.setVerticalGroup(
            panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_BuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelVistaProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panel_menu.setBackground(java.awt.Color.darkGray);
        panel_menu.setMinimumSize(new java.awt.Dimension(300, 500));

        bt_cerrarMenu.setBackground(java.awt.Color.darkGray);
        bt_cerrarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_cerrarMenuMouseClicked(evt);
            }
        });

        icon_cerrarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-button.png"))); // NOI18N
        icon_cerrarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon_cerrarMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon_cerrarMenuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bt_cerrarMenuLayout = new javax.swing.GroupLayout(bt_cerrarMenu);
        bt_cerrarMenu.setLayout(bt_cerrarMenuLayout);
        bt_cerrarMenuLayout.setHorizontalGroup(
            bt_cerrarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_cerrarMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_cerrarMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bt_cerrarMenuLayout.setVerticalGroup(
            bt_cerrarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_cerrarMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_cerrarMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bt_PanelAdmin.setBackground(java.awt.Color.darkGray);

        icon_PanelAdmin.setForeground(new java.awt.Color(255, 255, 255));
        icon_PanelAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/setting.png"))); // NOI18N
        icon_PanelAdmin.setText("Administrar Tienda");
        icon_PanelAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_PanelAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon_PanelAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon_PanelAdminMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bt_PanelAdminLayout = new javax.swing.GroupLayout(bt_PanelAdmin);
        bt_PanelAdmin.setLayout(bt_PanelAdminLayout);
        bt_PanelAdminLayout.setHorizontalGroup(
            bt_PanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_PanelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_PanelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );
        bt_PanelAdminLayout.setVerticalGroup(
            bt_PanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_PanelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_PanelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_menuLayout = new javax.swing.GroupLayout(panel_menu);
        panel_menu.setLayout(panel_menuLayout);
        panel_menuLayout.setHorizontalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_menuLayout.createSequentialGroup()
                        .addComponent(bt_cerrarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(bt_PanelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_menuLayout.setVerticalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_cerrarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_PanelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(410, Short.MAX_VALUE))
        );

        panel_Admin.setBackground(new java.awt.Color(51, 51, 51));

        panel_menuOpciones.setBackground(new java.awt.Color(51, 51, 51));

        bt_Productos.setBackground(new java.awt.Color(51, 51, 51));

        icon_Productos.setForeground(new java.awt.Color(255, 255, 255));
        icon_Productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cardboard.png"))); // NOI18N
        icon_Productos.setText("Productos");
        icon_Productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_ProductosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bt_ProductosLayout = new javax.swing.GroupLayout(bt_Productos);
        bt_Productos.setLayout(bt_ProductosLayout);
        bt_ProductosLayout.setHorizontalGroup(
            bt_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_ProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_Productos, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        bt_ProductosLayout.setVerticalGroup(
            bt_ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_ProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_Productos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_menuOpcionesLayout = new javax.swing.GroupLayout(panel_menuOpciones);
        panel_menuOpciones.setLayout(panel_menuOpcionesLayout);
        panel_menuOpcionesLayout.setHorizontalGroup(
            panel_menuOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_menuOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_Productos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_menuOpcionesLayout.setVerticalGroup(
            panel_menuOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuOpcionesLayout.createSequentialGroup()
                .addComponent(bt_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel_Activida.setBackground(java.awt.Color.darkGray);
        panel_Activida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        panel_AdminProductos.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 0));

        jTable1.setBackground(new java.awt.Color(255, 51, 153));
        jTable1.setForeground(new java.awt.Color(0, 153, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout panel_AdminProductosLayout = new javax.swing.GroupLayout(panel_AdminProductos);
        panel_AdminProductos.setLayout(panel_AdminProductosLayout);
        panel_AdminProductosLayout.setHorizontalGroup(
            panel_AdminProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_AdminProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_AdminProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_AdminProductosLayout.setVerticalGroup(
            panel_AdminProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AdminProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_ActividaLayout = new javax.swing.GroupLayout(panel_Activida);
        panel_Activida.setLayout(panel_ActividaLayout);
        panel_ActividaLayout.setHorizontalGroup(
            panel_ActividaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ActividaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_AdminProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_ActividaLayout.setVerticalGroup(
            panel_ActividaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ActividaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_AdminProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bt_VolverPanelVenta.setBackground(java.awt.Color.darkGray);

        icon_VolverPanelVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return.png"))); // NOI18N

        javax.swing.GroupLayout bt_VolverPanelVentaLayout = new javax.swing.GroupLayout(bt_VolverPanelVenta);
        bt_VolverPanelVenta.setLayout(bt_VolverPanelVentaLayout);
        bt_VolverPanelVentaLayout.setHorizontalGroup(
            bt_VolverPanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_VolverPanelVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_VolverPanelVenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bt_VolverPanelVentaLayout.setVerticalGroup(
            bt_VolverPanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_VolverPanelVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_VolverPanelVenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_AdminLayout = new javax.swing.GroupLayout(panel_Admin);
        panel_Admin.setLayout(panel_AdminLayout);
        panel_AdminLayout.setHorizontalGroup(
            panel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AdminLayout.createSequentialGroup()
                .addComponent(panel_menuOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Activida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panel_AdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_VolverPanelVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_AdminLayout.setVerticalGroup(
            panel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_VolverPanelVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_Activida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_menuOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(522, Short.MAX_VALUE)
                .addComponent(panel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_Admin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_Admin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /*Botones de uso de interfaz y elementos visuales -----------------------------------------------------------------*/
    //Simula un botón
    private void bt_MenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_MenuMouseEntered
        // TODO add your handling code here:
        bt_Menu.setBackground(Color.GRAY);
    }//GEN-LAST:event_bt_MenuMouseEntered

    private void bt_MenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_MenuMouseExited
        // TODO add your handling code here:
        if(!panel_menu.isVisible()){
            bt_Menu.setBackground(Color.darkGray);
        }
    }//GEN-LAST:event_bt_MenuMouseExited

    private void bt_CancelarCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CancelarCompraMouseEntered
        // TODO add your handling code here:
        bt_CancelarCompra.setBackground(Color.GRAY);
    }//GEN-LAST:event_bt_CancelarCompraMouseEntered

    private void bt_CancelarCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CancelarCompraMouseExited
        // TODO add your handling code here:
        bt_CancelarCompra.setBackground(Color.darkGray);
    }//GEN-LAST:event_bt_CancelarCompraMouseExited

    private void bt_BuscarProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_BuscarProductoMouseEntered
        // TODO add your handling code here:
        bt_BuscarProducto.setBackground(Color.GRAY);
    }//GEN-LAST:event_bt_BuscarProductoMouseEntered

    private void bt_BuscarProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_BuscarProductoMouseExited
        // TODO add your handling code here:
        bt_BuscarProducto.setBackground(Color.darkGray);
    }//GEN-LAST:event_bt_BuscarProductoMouseExited

    private void bt_MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_MenuMouseClicked
        // TODO add your handling code here:
        panel_menu.setVisible(true);
        //bt_Menu.setVisible(false);
    }//GEN-LAST:event_bt_MenuMouseClicked

    private void bt_cerrarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cerrarMenuMouseClicked
        // TODO add your handling code here:
        panel_menu.setVisible(false);
        bt_Menu.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_bt_cerrarMenuMouseClicked

    private void icon_PanelAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_PanelAdminMouseClicked
        // TODO add your handling code here:
        panelVenta.setVisible(false);
        panel_menu.setVisible(false);
        panel_Admin.setVisible(true);
    }//GEN-LAST:event_icon_PanelAdminMouseClicked

    private void tf_BuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_BuscarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_BuscarProductoActionPerformed

    private void bt_EliminarProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_EliminarProductoMouseEntered
        // TODO add your handling code here:
        bt_EliminarProducto.setBackground(Color.GRAY);
    }//GEN-LAST:event_bt_EliminarProductoMouseEntered

    private void bt_EliminarProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_EliminarProductoMouseExited
        // TODO add your handling code here:
        bt_EliminarProducto.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_bt_EliminarProductoMouseExited

    private void tf_BuscarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_BuscarProductoMouseClicked
        // TODO add your handling code here:
        tf_BuscarProducto.setFocusable(true);
    }//GEN-LAST:event_tf_BuscarProductoMouseClicked

    private void icon_PanelAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_PanelAdminMouseEntered
        // TODO add your handling code here:
        bt_PanelAdmin.setBackground(Color.GRAY);
    }//GEN-LAST:event_icon_PanelAdminMouseEntered

    private void icon_PanelAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_PanelAdminMouseExited
        // TODO add your handling code here:
        bt_PanelAdmin.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_icon_PanelAdminMouseExited

    private void icon_cerrarMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_cerrarMenuMouseEntered
        // TODO add your handling code here:
        bt_cerrarMenu.setBackground(Color.GRAY);
    }//GEN-LAST:event_icon_cerrarMenuMouseEntered

    private void icon_cerrarMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_cerrarMenuMouseExited
        // TODO add your handling code here:
        bt_cerrarMenu.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_icon_cerrarMenuMouseExited

    private void icon_ProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_ProductosMouseClicked
        // TODO add your handling code here:
        bt_Productos.setBackground(Color.decode("#0099CC"));
    }//GEN-LAST:event_icon_ProductosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lab_BuscarProducto;
    private javax.swing.JPanel PanelCategoria;
    private javax.swing.JPanel PanelVistaProductos;
    private javax.swing.JPanel Producto;
    private javax.swing.JPanel bt_BuscarProducto;
    private javax.swing.JPanel bt_CancelarCompra;
    private javax.swing.JPanel bt_EliminarProducto;
    private javax.swing.JPanel bt_Menu;
    private javax.swing.JPanel bt_PanelAdmin;
    private javax.swing.JPanel bt_Productos;
    private javax.swing.JPanel bt_RetornoVategoria;
    private javax.swing.JPanel bt_VolverPanelVenta;
    private javax.swing.JPanel bt_cerrarMenu;
    private javax.swing.JLabel icon_BuscarProducto;
    private javax.swing.JLabel icon_CancelarCompra;
    private javax.swing.JLabel icon_EliminarProducto;
    private javax.swing.JLabel icon_PanelAdmin;
    private javax.swing.JLabel icon_Productos;
    private javax.swing.JLabel icon_VolverPanelVenta;
    private javax.swing.JLabel icon_cerrarMenu;
    private javax.swing.JLabel icon_menu;
    private javax.swing.JLabel impuestos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labTotal;
    private javax.swing.JLabel lab_Impuestos;
    private javax.swing.JLabel lab_SubTotal;
    private javax.swing.JLabel listaVacia;
    private javax.swing.JPanel panelEditArticulos;
    private javax.swing.JPanel panelEditCompra;
    private javax.swing.JPanel panelLista;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JPanel panelSumaCostos;
    private javax.swing.JPanel panelVenta;
    private javax.swing.JPanel panel_Activida;
    private javax.swing.JPanel panel_Admin;
    private javax.swing.JPanel panel_AdminProductos;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JPanel panel_menuOpciones;
    private javax.swing.JLabel subTotal;
    private javax.swing.JTextField tf_BuscarProducto;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
