package UI;

import ingenieria_caja_registradora.ConexionBase;
import ingenieria_caja_registradora.ImagenTabla;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Blob;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class PantallaCarga1 extends javax.swing.JFrame {

    ConexionBase ConSQL = new ConexionBase();
    Connection Conect;
    int Idc;
    String Ruta = "";

    DefaultTableModel Modelo;

    public PantallaCarga1() {
        initComponents();
        setLocationRelativeTo(null);
        ConsultaBase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setEnabled(false);
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 600));

        jLabel2.setText("Ejemplo Base de datos");

        jLabel3.setText("Producto: ");

        jButton2.setText("Imagen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Descripcion:");

        jLabel5.setText("Cantidad");

        jLabel6.setText("ID:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton3.setText("INSERTAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("ELIMINAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("CAMBIAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setText("Precio:        $");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Imagen", "Descripcion", "Cantidad", "ID", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setPreferredSize(new java.awt.Dimension(100, 100));

        jButton1.setText("ELIMINAR TODO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(57, 57, 57)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jButton2))))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //BOTON PARA ESCOGER UNA IMAGEN DEL EXPLORADOR DE ARCHIVOS
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser File = new JFileChooser();             //TEXTO QUE SE MOSTRAR EN EL EXPLORADOR , EXTENSIONES PERMITIDAS
        FileNameExtensionFilter Filtro = new FileNameExtensionFilter("JPG,PNG,GIF", "jpg", "png", "gif");
        File.setFileFilter(Filtro);
        int Respuesta = File.showOpenDialog(this);
        if (Respuesta == JFileChooser.APPROVE_OPTION) {
            Ruta = File.getSelectedFile().getAbsolutePath();
            Image Imagen = new ImageIcon(Ruta).getImage();
            ImageIcon Icon = new ImageIcon(Imagen.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), 0));
            jLabel1.setIcon(Icon);
        }

    }//GEN-LAST:event_jButton2ActionPerformed
    //BOTON PARA AGREGAR DATOS
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        agregar();
        jLabel1.setIcon(null);
        jTextArea1.setText("");
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        Ruta = "";
        ConsultaBase();
    }//GEN-LAST:event_jButton3ActionPerformed
    //BOTON PARA CAMBIAR UN DATO
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ModificarDato();
        jLabel1.setIcon(null);
        jTextArea1.setText("");
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        Ruta = "";
        ConsultaBase();
    }//GEN-LAST:event_jButton5ActionPerformed
    //ESTA PARTE SIRVE PARA SELECCIONAR UN DATO EN LA TABLA
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int Fila = jTable1.getSelectedRow();
        if (Fila == -1) {
            JOptionPane.showMessageDialog(null, "No se selecciono nada");
        } else {
            JLabel ImagenTabla = (JLabel) jTable1.getValueAt(Fila, 0);
            String Descripcion = (String) jTable1.getValueAt(Fila, 1);
            int Cantidad = Integer.parseInt((String) jTable1.getValueAt(Fila, 2).toString());
            Idc = Integer.parseInt((String) jTable1.getValueAt(Fila, 3).toString());
            float Precio = Float.parseFloat((String) jTable1.getValueAt(Fila, 4).toString());

            jLabel1.setIcon(ImagenTabla.getIcon());
            jTextArea1.setText(Descripcion);
            jTextField1.setText("" + Cantidad);
            jTextField2.setText("" + Idc);
            jTextField3.setText("" + Precio);
        }
    }//GEN-LAST:event_jTable1MouseClicked
    //BOTON QUE ELIMINA UN DATO
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        EliminarDato();
        jLabel1.setIcon(null);
        jTextArea1.setText("");
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        Ruta = "";
        ConsultaBase();
    }//GEN-LAST:event_jButton4ActionPerformed
    //BOTON DE ELIMINAR TODO
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EliminarTodo();
        ConsultaBase();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaCarga1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaCarga1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaCarga1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaCarga1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaCarga1().setVisible(true);
            }
        });
    }

    //METODO PARA CONSULTAR LOS DATOS EN LA BASE DE DATOS Y MOSTRARLOS EN UNA TABLA
    public void ConsultaBase() {
        Conect = ConSQL.ConexionBase();
        ResultSet Rs = ConSQL.Visualizar();

        jTable1.setDefaultRenderer(Object.class, new ImagenTabla());
        try {
            Object[] producto = new Object[5];
            Modelo = (DefaultTableModel) jTable1.getModel();
            while (Rs.next()) {
                
                Blob blob = Rs.getBlob("Imagen");
                if (blob != null) {
                    try {
                        byte[] data = blob.getBytes(1, (int) blob.length());
                        BufferedImage Img = null;
                        try {
                            Img = ImageIO.read(new ByteArrayInputStream(data));
                        } catch (Exception e) {
                        }
                        
                        ImageIcon Icon = new ImageIcon(Img.getScaledInstance(100, 100, 0));
                        producto[0] = new JLabel(Icon);
                        producto[1] = Rs.getString("Descripcion");
                        producto[2] = Rs.getInt("Cantidad");
                        producto[3] = Rs.getInt("Id");
                        producto[4] = Rs.getFloat("Precio");
                        
                    } catch (Exception e) {
                        producto[0] = "No imagen";
                    }

                } else {
                    producto[0] = "No imagen";
                }

                Modelo.addRow(producto);
            }
            jTable1.setModel(Modelo);
            jTable1.setRowHeight(100);

        } catch (Exception e) {
            System.out.println("Error para mostrar Datos");
        }
    }

    //METODO PARA AGREGAR DATOS A LA BASE DE DATOS
    public void agregar() {
        ConexionBase CB = new ConexionBase();

        Icon Imagen = jLabel1.getIcon();
        String Des = jTextArea1.getText();
        String Cant = jTextField1.getText();
        String Id = jTextField2.getText();
        String Precio = jTextField3.getText();

        try {
            if (Imagen == null || Des.equals("") || Cant.equals("") || Id.equals("") || Precio.equals("")) {
                JOptionPane.showMessageDialog(null, "Ingresa los datos que faltan");
            } else {
                CB.GuardarInformacion(Ruta, Des, Integer.valueOf(Cant), Integer.valueOf(Id), Integer.valueOf(Precio));
                JOptionPane.showMessageDialog(null, "Datos ingresados correctamente");
                LimpiaTabla();
            }
        } catch (Exception e) {
        }
    }

    //METODO PARA LIMPIAR LA TABLA CUANDO SE INSERTEN DATOS NUEVOS Y SE MUESTREN
    public void LimpiaTabla() {
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            Modelo.removeRow(i);
            i -= 1;
        }
    }
   //METODO PARA HACER EL CAMBIO DE DATO
    public void ModificarDato() {
        ConexionBase CB = new ConexionBase();

        Icon Imagen = jLabel1.getIcon();
        String Des = jTextArea1.getText();
        String Cant = jTextField1.getText();
        String Precio = jTextField3.getText();

        try {
            if (Imagen == null || Des.equals("") || Cant.equals("") || Precio.equals("")) {
                JOptionPane.showMessageDialog(null, "Ingresa los datos que faltan");
            } else {
                CB.ModificarInformacion(Ruta, Des, Integer.valueOf(Cant), Idc, Float.valueOf(Precio));
                JOptionPane.showMessageDialog(null, "Datos cambiados correctamente");
                LimpiaTabla();
            }
        } catch (Exception e) {
        }
    }
   //METODO PARA ELIMINAR EL DATO
    public void EliminarDato() {
        ConexionBase CB = new ConexionBase();
        int Fila = jTable1.getSelectedRow();
        try {
            if (Fila < 0) {
                JOptionPane.showMessageDialog(null, "Ningun dato seleccionado");
                LimpiaTabla();
            } else {
                CB.EliminarInformacion(Idc);
                JOptionPane.showMessageDialog(null, "Dato eliminado correctamente");
                LimpiaTabla();
            }
        } catch (Exception e) {
        }
    }
   //METODO PARA ELIMINAR LA TABLA
    public void EliminarTodo() {
        ConexionBase CB = new ConexionBase();
        CB.BorraTodo();
        LimpiaTabla();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
